### ISSUE TITLE
older Git versions don't understand `git show -q`

### ISSUE THREAD

**Issue by torbjoernk** [ivantsepp/jekyll-git_metadata#10]
Older (ancient) versions of Git (e.g. 1.8.4) don't understand the `--quiet|-q` argument of `git show`. The alternative is to use `--no-patch`, which seems upwards compatible.

**Comment by ivantsepp** [comment]
Thanks for reporting this and sorry for the long delay. I've been out of it. Fixed in https://github.com/ivantsepp/jekyll-git_metadata/commit/d9059c795b1da251c23d9f8ada58594de6557ce4
