### ISSUE TITLE
Not working with Jekyll >= 3.0.0

### ISSUE THREAD

**Issue by JaimeObregon** [ivantsepp/jekyll-git_metadata#11]
Cool feature! However, it won't work with Jekyll >=3.0.0 (released on January 2015):

```
/usr/local/lib/site_ruby/2.1.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate jekyll-git_metadata-0.0.3, because jekyll-3.0.3 conflicts with jekyll (~> 2.0) (Gem::ConflictError)
```

From `jekyll-git_metadata.gemspec`:

```
spec.add_dependency "jekyll", '~> 2.0'
```

**Comment by JaimeObregon** [comment]
It seems #9 fixes this issue. If would be great if you could merge that pull request and publish the resulting gem, @ivantsepp. Thank you!

**Comment by sn0w** [comment]
@ivantsepp Can you merge/review #9 please?

**Comment by ivantsepp** [comment]
Sorry y'all for the long wait, I've been out of it 😢 . Merged and released https://rubygems.org/gems/jekyll-git_metadata/versions/0.1.0
