### ISSUE TITLE
Request: List of recently modified posts/pages/documents

### ISSUE THREAD

**Issue by seltzy** [ivantsepp/jekyll-git_metadata#12]
I'm hoping to add functionality to my blog that not only shows recent posts, but also files that have recently been included in a commit. A sort of "recently modified" list would be possible. That way readers could see when a page or post or collection document has been recently modified.

**Comment by ivantsepp** [comment]
I added `changed_files` to commit data in #13. Hopefully that should work for your use case. Release `v0.1.2`
