### ISSUE TITLE
Github pages support

### ISSUE THREAD

**Issue by jonaprieto** [ivantsepp/jekyll-git_metadata#22]
Hi,
I might be doing something wrong but with this plugin using
the local server I can retrieve the git metadata but when
I push my site to GitHub-pages, there isn't any information at all.

My repository is this one: https://github.com/jonaprieto/jonaprieto.github.io

Best,

Jonathan.

local:

![image](https://user-images.githubusercontent.com/1428088/38823282-42e3b566-41a6-11e8-80e1-aff1696d6766.png)

online:

![image](https://user-images.githubusercontent.com/1428088/38823301-4eea3c40-41a6-11e8-93ab-808a7e183a8a.png)

**Comment by alexwlchan** [comment]
GitHub Pages doesn’t support arbitrary plugins. Quoting [their docs](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/):

> GitHub Pages officially supports the Jekyll plugins found in the GitHub Pages gem. For the exact versions of the Jekyll plugins that GitHub Pages supports, see this list of GitHub Pages dependencies. Other plugins are not supported, so the only way to incorporate them in your site is to generate your site locally and then push your site's static files to your GitHub Pages site.

**Comment by jonaprieto** [comment]
Yes, you're right.
